export const GET_QUESTIONS = 'GET_QUESTIONS';
export const FILTER_QUESTIONS = 'FILTER_QUESTIONS';
export const SAVE_QUESTION_ANSWER = 'SAVE_QUESTION_ANSWER';
export const SAVE_QUESTION = 'SAVE_QUESTION';
